"""
Built-in check types for Agathos directives.

Each check type has a schema defining required/optional fields.
The setup prompt includes this schema so the agent knows what to generate.
"""

from typing import Dict, Any, List

# YAML schema for directives.yaml
DIRECTIVES_SCHEMA: str = """
# AGATHOS Prime Directives
# Generated by agent on `orthrus setup`. Edit freely.
# Reloaded on every Agathos poll cycle — no restart needed.

# Natural-language prime directive. Shown in corrective prompts.
prime_directive: |
  Every substantive interaction must produce measurable output.

# List of checks. Each runs every poll cycle against session data.
checks:

  # --- Quality checks (read from holographic_memory.db) ---
  - name: quality_gate
    type: quality_threshold
    metric: avg_quality              # AVG(quality_score) from facts table
    threshold: 0.92
    window: 2h                       # SQL datetime modifier
    severity: warning                # warning | critical
    enabled: true

  - name: trajectory_generation
    type: count_threshold
    table: trajectories              # holographic_memory.db table
    min_count: 2
    window: 2h
    quality_threshold: 0.92          # optional: only count rows above this
    severity: warning
    enabled: true

  - name: fact_extraction
    type: count_threshold
    table: facts
    min_count: 1
    window: 30m
    quality_threshold: 0.92
    severity: warning
    enabled: true

  # --- Entropy checks (read from orthrus.db) ---
  - name: repeat_tool_calls
    type: entropy_threshold
    entropy_type: repeat_tool_calls
    min_count: 3
    window: 10m
    severity: warning
    enabled: true

  - name: error_cascade
    type: entropy_threshold
    entropy_type: error_cascade
    min_count: 3
    window: none                     # sequential, not time-windowed
    severity: warning
    enabled: true

  - name: budget_pressure
    type: budget_threshold
    warning_ratio: 0.70
    critical_ratio: 0.85
    near_exhaustion_ratio: 0.90
    enabled: true

  # --- Custom checks (Python plugins) ---
  # Drop .py files in the custom_checks_dir.
  # Each file must define: def check(session_id, cursor, config) -> dict
  #   Returns: {"check_type": str, "passed": bool, "details": str}
  # custom_checks_dir: ~/.hermes/orthrus/checks/

# Sessions to ignore (glob patterns on session_id)
# ignore:
#   - "cron_legacy_*"
#   - "manual_test_*"
"""

# Check type definitions for validation and agent guidance
BUILTIN_CHECK_TYPES = {
    "quality_threshold": {
        "description": "Check average quality_score against a threshold in holographic_memory.db",
        "required": ["metric", "threshold", "window"],
        "optional": ["severity", "enabled"],
        "defaults": {"severity": "warning", "enabled": True},
    },
    "count_threshold": {
        "description": "Check row count in a holographic_memory.db table",
        "required": ["table", "min_count", "window"],
        "optional": ["quality_threshold", "severity", "enabled"],
        "defaults": {"severity": "warning", "enabled": True},
    },
    "entropy_threshold": {
        "description": "Check entropy detection count in orthrus.db",
        "required": ["entropy_type", "min_count"],
        "optional": ["window", "severity", "enabled"],
        "defaults": {"window": "10m", "severity": "warning", "enabled": True},
    },
    "budget_threshold": {
        "description": "Check iteration budget burn rate",
        "required": [],
        "optional": ["warning_ratio", "critical_ratio", "near_exhaustion_ratio", "enabled"],
        "defaults": {
            "warning_ratio": 0.70,
            "critical_ratio": 0.85,
            "near_exhaustion_ratio": 0.90,
            "enabled": True,
        },
    },
}
